#ifndef RE_MINECRAFT_CHUNKSTATE_H
#define RE_MINECRAFT_CHUNKSTATE_H

enum class ChunkState {
    EMPTY,
    GENERATING,
    GENERATED,
    MESHING,
    READY,
    UNLOADING
};

#endif //RE_MINECRAFT_CHUNKSTATE_H